### ISSUE TITLE
NZB-Monkey issue with NZBindex TimeOut

### ISSUE THREAD

**Issue by bundyboss** [nzblnk/nzb-monkey#10]
Hi, 
I've just see that I've a problem with Nzbindex and nzbking servers:
On each search I've this message:
- Searching NZB - Search for best NZB enabled
   with NZBIndex ... Timeout
   with NZBKing ... Timeout

But I could browse the website for nzbindex. NZBking seems to be down!
Could you have a look?

Thanks a lot

**Comment by prime0n** [comment]
maybe a new name for the same problem?


I have realy often this problem:
```
...
   - Searching NZB - Search for best NZB enabled
   with BinSearch - Alternative Server ... Connection Error
   with NZBKing ... Connection Error
   with NZBIndex ... Connection Error
   with NZBIndex Beta ... Connection Error
...
```
