### ISSUE TITLE
Suggestion: Docker Container

### ISSUE THREAD

**Issue by grasshide** [nzblnk/nzb-monkey#16]
I love nzb-monkey, but I hate that I can only use it on my windows pc. I'd rather use it everywhere - including my mobile phone. To achieve this a simple docker container with a lightweight webserver should be enough. It doesn't need more than an input filed on the start page where the nzblnk can be put. The config can be in a fix text file at first. Later on, a config page would be nice. The output of the script can be shown in a simple text field.

**Comment by nzblnk** [comment]
There is now a project called "Tarsier" covering the need of the monkey on a mobile platform.

This idea should be a seperate project and not part of the monkey project itself. Maybe someone takes this idea and creates a project on top of the monkey.
