### ISSUE TITLE
SRR (ReScene) Integration

### ISSUE THREAD

**Issue by Lorenz1508** [nzblnk/nzb-monkey#21]
what is ReScene
Basicly the gist of this program is that rar files that use store compression can be recreated with a special small file called ".srr"
All you need to do is let the program process the rar's (or an sfv file) and it will create a .srr file which can later be used for reconstruction.

The implications are awesome, you can extract and delete the original rars and if you want you can recreate them with this <10kb file!
a lot of 'collectors' or 'archivers' would appreciate a feature like this.

**Comment by nzblnk** [comment]
Thank you for the suggestion. But this is more a feature for the tool that handles the RAR archives. Please request this on the NZBGet or SAbNZBd communities. The NZB-Monkey is only for fetching the NZB files.
