### ISSUE TITLE
Latest version not working any more nzbking

### ISSUE THREAD

**Issue by teaborn2** [nzblnk/nzb-monkey#26]
The latest version 0.2.5 isn't working on nzbking. It always results in "NOT FOUND". I think they changed their site 2 weeks ago.

**Comment by macearl** [comment]
I also noticed this and had a bit of time today, so i took a look at it.
This PR should fix it: https://github.com/nzblnk/nzb-monkey/pull/27

**Comment by teaborn2** [comment]
I tested your PR and can confirm that it is working again with nzbking. Thank you

**Comment by nzblnk** [comment]
I merged @macearl 's PR into the current release v0.2.6. Thanks again, macearl.
