### ISSUE TITLE
No cfg file created on ubuntu

### ISSUE THREAD

**Issue by hollysheep** [nzblnk/nzb-monkey#28]
i tried nzb-monkey for the first time on ubuntu. all worked fine after i had installed the missing modules

```
 - Write desktop file to '/home/user/.local/share/applications/nzblnk.desktop'
   ... DONE
 - Add nzblnk to mimeapps.list ... DONE
Configuration successfully finished.
```

but there is no cfg file in the nzb-monkey folder.

**Comment by nzblnk** [comment]
Hi @hollysheep,

the config file itself is generated after the first launch of `nzbmonkey.py`. Just checked this with Ubuntu 20.04. ✔️
