### ISSUE TITLE
NZBKing search - Problems with underscore

### ISSUE THREAD

**Issue by plintogo** [nzblnk/nzb-monkey#3]
If a search string contains an underscore nzbking returns no search results.
If I replace them with a space nzbking returns search results.

**Comment by z1atk0** [comment]
This breaks searching with at least nzbindex, for example "m4Q3GZbv_3": search manually, exactly one hit. Search with the monkey, "NOT  FOUND". Maybe the fix should be made engine-specific instead of global.
