### ISSUE TITLE
[Question] Android-App

### ISSUE THREAD

**Issue by danielkastner** [nzblnk/nzb-monkey#31]
Hi.
I'm working on an App for Android to handle NZBLNKs like your nzb-monkey for Windows. And I'd like to know if it is fine for you if I use the name and the icon/logo?

Regards,
Daniel

**Comment by nzblnk** [comment]
Hi Daniel,

I am not sure if your are aware that [there is already an app](https://play.google.com/store/apps/details?id=com.kroegerama.nzblnk) acting like the NZB Monkey.

If you create a MIT (or similar) licenced app as opensource, please feel free to use the NZB Monkey assets but make sure to give some credits in the app.

If you create a commercial and/or close source app, we can't give you permission to use our NZB Monkey assets, sorry.

In both cases your are allowed to use the NZBLNK logo for NZBLNK relevant actions in the app. Please reference here also the credits for the NZBLNK technology in your credits/about screen. Feel free to contact us (here or via [NZBLNK issues](https://github.com/nzblnk/nzblnk.github.io/issues)) if you need the assets as a vector image (SVG) or some higher resolution pixel images (PNG).

**Comment by danielkastner** [comment]
OK, thank you for your reply
