### ISSUE TITLE
nzbindex problems

### ISSUE THREAD

**Issue by HengeDK** [nzblnk/nzb-monkey#33]
nzb-monkey can't find this file a02c9aacd4e64384bc662f2d52da021a
it's possible to find it with manual search on nzbindex but not via nzb-monkey

**Comment by macearl** [comment]
The search URL for nzbindex is set such that only complete entries will be returned 
https://github.com/nzblnk/nzb-monkey/blob/c66ca3a7ded291d591d696ac48ed901a4467e55b/src/nzbmonkey.py#L774

If you manually search for this Header you will see that there are "only" 61916 out of 61918 parts available and therefore it is marked as incomplete

excerpt from the xml the search returns:
```
[...]
<total_parts>61918</total_parts>
<available_parts>61916</available_parts>
<complete>0</complete>
[...]
```

If you also want to include incomplete entries in your search you just need to remove the `complete=1` part from the line i linked above

**Comment by HengeDK** [comment]
thanks for your answer
is it possible to search for 99% ?
if I download the file it is complete and other indexer find it 100%
only nzbindex says 99%

**Comment by macearl** [comment]
Sorry can't really answer that.
My guess would be no. For all supported indexers there is only a `searchUrl` defined, which has to be provided by the indexer. Seeing as there are no further options in the advanced search on nzbindex to filter for `X`% complete. One could theoretically parse the xml output further and do some calculations based on the `available_parts` and `total_parts` values.
That however is probably out of scope for this tool

**Comment by HengeDK** [comment]
thanks !
