### ISSUE TITLE
Add Watcher, sonarr,... compatibility

### ISSUE THREAD

**Issue by bundyboss** [nzblnk/nzb-monkey#9]
Hello,
I think it could be a good idea to add nzb-monkey support in Watcher and Sonarr. Some french sites are using nzblnk instead of giving directly the NZB.
With this new fonctionality we will be able to automatise our download using all format!

If you need support for testing (site with nzblnk) I could provide one!
Thanks for your tool!

**Comment by nzblnk** [comment]
@bundyboss [Watcher](https://github.com/nosmokingbandit/watcher3) and [Sonarr](https://sonarr.tv/) are systems to "snatch" NZB sources of the titles you want. NZB Monkey is for **manually** add NZBs to your downloading solution (SabNZBd, NZBGet, etc). Please explain a bit more in detail how the Monkey can be improved to be compatible to Watcher/Sonarr/etc solutions.

**Comment by bundyboss** [comment]
Yes they snatch a NZB like that:
extract of api access:
<link>
https://mywebsite/getnzb/bfxxxxxxxxxxxxxxxxxxxxxxxx.nzb&i=1&r=myprivatekey
</link>

So it's possible to add or change the link in the api access by (each web site must do that):
<link2>
nzblnk:?t=MySearch&h=MySearchInBinSearch
</link2>
Watcher,Sonarrr could take this like and put it in nzb-monkey.
Some French sites could not give directly a NZB file (could be interpreted like piracy). So a NZBlnk could be the solution.

If you want a test site for api access. Let me know I could create an access.
